adminUser: admin
adminPassword: healthcare-dev

service:
  type: ClusterIP

persistence:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

datasources:
  datasources.yaml:
    apiVersion: 1

    datasources:

      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.observability.svc.cluster.local
        isDefault: true

      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki-gateway.observability.svc.cluster.local

      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3200

        jsonData:
          tracesToLogsV2:
            datasourceUid: loki

          tracesToMetrics:
            datasourceUid: prometheus

          serviceMap:
            datasourceUid: prometheus